### ISSUE TITLE
State and last_event time not match

### ISSUE THREAD

**Issue by miguelangellv** [slinkymanbyday/badnest#4]
I don't know why, but, sometimes the state not update with the last event time

![image](https://user-images.githubusercontent.com/638110/83735890-35005f00-a651-11ea-8604-aca67af2ba6f.png)

**Comment by slinkymanbyday** [comment]
Seems like it was getting the first event in the last hour instead of the last event for this status. will push a fix over the weekend.

**Comment by miguelangellv** [comment]
Perfect. Thanks!
