### ISSUE TITLE
http to rtsp

### ISSUE THREAD

**Issue by stvnmbr1** [slinkymanbyday/badnest#5]
ffmpeg  -i "http://[stream.url]" -vcodec libx264 -tune zerolatency -b 900k -f mpegts udp://127.0.0.1:10000

don't know if we could have something like this that translates the http stream to rtsp in python?

**Comment by stvnmbr1** [comment]
https://www.home-assistant.io/integrations/ffmpeg/

https://github.com/kkroening/ffmpeg-python

**Comment by slinkymanbyday** [comment]
Happy for you to look into this further, I probably won't be able to dedicate time to working on streaming support. I'm happy waiting for https://developers.google.com/nest/device-access to become a reality.

**Comment by stvnmbr1** [comment]
Ah yes, forgot about this one, as badnest actually works great .. only a
few months left by now!
You can close this ;)

Thanks for everything!


Op zo 14 jun. 2020 15:42 schreef slinkymanbyday <notifications@github.com>:
